Feature/41191
UrvashiChaudhary/javascript-client pull request #15
Opened 2021-01-04 13:00 UTC by UrvashiChaudhary

Add following new props to the table component:
1. actions: Optional, list of actions to be rendered along with their handlers
2. count: No. of total records (Numeric), if count is 0 then don’t show the pagination.
3. page: Current Page, default to 0
4. rowsPerPage: No. of records per page, default to 100
5. onChangePage: handler to be called and update the page in the state.

In actions provide two actions i.e Edit and Remove,
- on Edit Handler, open the Edit Dialog prefilled with name and email, and in case of submit, show the the update data, in the “TraineeList” component,
- while for Remove Handler show the confirm Dialog Box, with cancel and Delete option. If Delete is clicked, then show the deleted item details in the console

Please refer to the attached GIFs.

Please note two more components need to be created adjacent to “AddDialog”, and they named as “EditDialog” and “RemoveDialog” respectively.

2021-01-13 10:09 UTC, adilsuccessive requested changes
if count is 0 then don’t show the pagination.
is not working

2021-01-13 10:09 UTC, adilsuccessive commented on training/src/pages/Trainee/TraineeList.jsx
> +  handleChangePage = (event, newPage) => {
event is not used.

2021-01-13 10:09 UTC, adilsuccessive commented on training/src/pages/Trainee/TraineeList.jsx
> +  handleRemoveDialogOpen = (element) => (event) => {
event is not used

2021-01-13 10:09 UTC, adilsuccessive commented on training/src/pages/Trainee/TraineeList.jsx
> +  handleEditDialogOpen = (element) => (event) => {
event is not used

2021-01-13 12:00 UTC, UrvashiChaudhary commented on training/src/pages/Trainee/TraineeList.jsx
> +  handleChangePage = (event, newPage) => {
done

2021-01-13 12:01 UTC, UrvashiChaudhary commented on training/src/pages/Trainee/TraineeList.jsx
> +  handleRemoveDialogOpen = (element) => (event) => {
done

2021-01-13 12:01 UTC, UrvashiChaudhary commented on training/src/pages/Trainee/TraineeList.jsx
> +  handleEditDialogOpen = (element) => (event) => {
done

2021-01-13 12:01 UTC, UrvashiChaudhary commented
> if count is 0 then don’t show the pagination.
> is not working

done

2021-01-15 09:38 UTC, adilsuccessive approved these changes

2021-01-15 09:38 UTC, merged